"""Tests for recording the interactive review's outcome in a sanitized HAR.

Test Coverage:
    - record_review: every outcome is written to sanitization.review with the
      user-decision counts, redactions are applied, and a compressed sibling
      is regenerated byte-for-byte from the reviewed file
    - Pass 1 records none_flagged when nothing was offered, and leaves the
      outcome unrecorded when values await review
    - Failures: unreadable or malformed input, a failed write (original kept,
      no temp file left), a failed compressed rewrite (StaleCompressedError)

Test Strategy:
    - Table-driven with @pytest.mark.parametrize
    - HAR and cases in tests/fixtures/test_review.json
"""

from __future__ import annotations

import copy
import gzip
import json
from pathlib import Path
from typing import Any

import pytest

from har_capture.sanitization import (
    ConfidenceLevel,
    FlaggedValue,
    RedactionStatus,
    ReviewOutcome,
    SanitizationReport,
    StaleCompressedError,
    record_review,
    sanitize_har_file,
)
from har_capture.sanitization.report import HeuristicMode

FIXTURES = json.loads((Path(__file__).parent.parent / "fixtures" / "test_review.json").read_text())
RECORD_CASES = FIXTURES["record_review_cases"]
PASS1_CASES = FIXTURES["pass1_review_cases"]
VALUE = FIXTURES["flagged_value"]


def _report(status: str = "flagged") -> SanitizationReport:
    """A report holding the fixture's one flagged value with the given status."""
    report = SanitizationReport(input_file="in.har", output_file="out.har", salt="review")
    report.flagged.append(
        FlaggedValue(
            original_value=VALUE,
            category="field",
            confidence=ConfidenceLevel.MEDIUM,
            context="username",
            reason="Flaggable field name",
            status=RedactionStatus(status),
        )
    )
    return report


def _write_pair(tmp_path: Path, *, sibling: bool = True) -> tuple[Path, Path]:
    """Write the sanitized HAR, plus a stale .gz of its pre-review content."""
    har_file = tmp_path / "device.sanitized.har"
    har_file.write_text(json.dumps(copy.deepcopy(FIXTURES["sanitized_har"])))
    gz_file = tmp_path / "device.sanitized.har.gz"
    if sibling:
        with gzip.open(gz_file, "wb") as f:
            f.write(har_file.read_bytes())
    return har_file, gz_file


class TestRecordReview:
    """Each outcome lands in the file with its counts, and the .gz follows."""

    @pytest.mark.parametrize("case", RECORD_CASES, ids=[c["id"] for c in RECORD_CASES])
    def test_outcome_recorded(self, tmp_path: Path, case: dict[str, Any]) -> None:
        har_file, gz_file = _write_pair(tmp_path)

        regenerated = record_review(har_file, _report(case["status"]), ReviewOutcome(case["outcome"]))

        written = json.loads(har_file.read_text())
        meta = written["log"]["_har_capture"]["sanitization"]
        assert meta["review"] == case["outcome"]
        assert meta["user_redacted"] == case["user_redacted"]
        assert meta["user_skipped"] == case["user_skipped"]
        assert (VALUE in har_file.read_text()) == case["value_kept"]
        assert regenerated == gz_file
        with gzip.open(gz_file, "rb") as f:
            assert f.read() == har_file.read_bytes()

    def test_explicit_compressed_path(self, tmp_path: Path) -> None:
        """The capture flow names its .gz; that one is rewritten."""
        har_file, _ = _write_pair(tmp_path, sibling=False)
        named = tmp_path / "upload.har.gz"
        named.write_bytes(b"stale")

        assert (
            record_review(har_file, _report("user"), ReviewOutcome.COMPLETED, compressed_path=named) == named
        )
        with gzip.open(named, "rb") as f:
            assert f.read() == har_file.read_bytes()

    def test_no_sibling_creates_none(self, tmp_path: Path) -> None:
        har_file, gz_file = _write_pair(tmp_path, sibling=False)

        assert record_review(har_file, _report(), ReviewOutcome.NO_TTY) is None
        assert not gz_file.exists()

    def test_log_without_metadata_gains_it(self, tmp_path: Path) -> None:
        """A sanitized file from another producer still records the outcome."""
        har_file = tmp_path / "foreign.har"
        har_file.write_text(json.dumps({"log": {"entries": []}}))

        record_review(har_file, _report(), ReviewOutcome.CANCELLED)

        assert (
            json.loads(har_file.read_text())["log"]["_har_capture"]["sanitization"]["review"] == "cancelled"
        )


class TestRecordReviewFailures:
    """A failure raises; the original file is never left half-written."""

    def test_missing_file(self, tmp_path: Path) -> None:
        with pytest.raises(OSError):
            record_review(tmp_path / "missing.har", _report(), ReviewOutcome.NO_TTY)

    @pytest.mark.parametrize(
        "text",
        ["{not json", '{"no_log": 1}', '{"log": []}'],
        ids=["invalid_json", "not_a_har", "log_not_object"],
    )
    def test_malformed_file(self, tmp_path: Path, text: str) -> None:
        bad = tmp_path / "bad.har"
        bad.write_text(text)

        with pytest.raises(ValueError):
            record_review(bad, _report(), ReviewOutcome.NO_TTY)

    def test_write_failure_keeps_original(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        har_file, _ = _write_pair(tmp_path, sibling=False)
        before = har_file.read_bytes()

        def fail_replace(self: Path, target: Path) -> Path:
            raise OSError("disk full")

        monkeypatch.setattr(Path, "replace", fail_replace)
        with pytest.raises(OSError, match="disk full"):
            record_review(har_file, _report("user"), ReviewOutcome.COMPLETED)
        monkeypatch.undo()

        assert har_file.read_bytes() == before
        assert sorted(p.name for p in tmp_path.iterdir()) == [har_file.name]

    def test_compressed_failure_names_the_stale_file(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        har_file, gz_file = _write_pair(tmp_path)

        def fail_open(*args: Any, **kwargs: Any) -> Any:
            raise OSError("disk full")

        monkeypatch.setattr(gzip, "open", fail_open)
        with pytest.raises(StaleCompressedError) as excinfo:
            record_review(har_file, _report("user"), ReviewOutcome.COMPLETED)

        assert excinfo.value.compressed_path == gz_file
        assert VALUE not in har_file.read_text(), "the reviewed .har is written before the .gz"


class TestPass1Review:
    """sanitize_har_file records none_flagged itself; anything else waits for a review."""

    @pytest.mark.parametrize("case", PASS1_CASES, ids=[c["id"] for c in PASS1_CASES])
    def test_pass1_review(self, tmp_path: Path, case: dict[str, Any]) -> None:
        entry = {
            "request": {
                "method": "POST",
                "url": "http://192.168.100.1/login",
                "headers": [],
                "postData": {"mimeType": "application/x-www-form-urlencoded", "text": case["text"]},
            },
            "response": {"status": 200, "headers": [], "content": {"mimeType": "text/html", "text": ""}},
        }
        raw = tmp_path / "raw.har"
        raw.write_text(json.dumps({"log": {"version": "1.2", "entries": [entry]}}))

        out, _ = sanitize_har_file(str(raw), str(tmp_path / "out.har"), heuristics=HeuristicMode.FLAG)

        meta = json.loads(Path(out).read_text())["log"]["_har_capture"]["sanitization"]
        assert meta.get("review") == case["review"]
