"""Pattern loading and hashing utilities for sanitization.

This module provides:
- Loading of PII patterns, sensitive fields, and allowlists from JSON
- Salted hash generation for correlation-preserving redaction
- Pattern merging for custom user patterns
"""

from __future__ import annotations

from har_capture.patterns.hasher import Hasher
from har_capture.patterns.loader import (
    PatternLoadError,
    clear_pattern_cache,
    compile_pattern,
    get_bloat_extensions,
    get_password_field_patterns,
    get_session_cookie_patterns,
    load_allowlist,
    load_capture_settings,
    load_pii_patterns,
    load_sensitive_patterns,
)
from har_capture.patterns.redaction import (
    EMAIL_RE,
    IPV6_RE,
    JSON_MAX_DEPTH,
    JSON_MAX_NESTING,
    MAC_RE,
    PRIVATE_IP_RE,
    PUBLIC_IP_RE,
    URL_VALUED_HEADERS,
    JsonObjectWithDuplicates,
    QueryCredential,
    QueryPayload,
    classify_identity_field,
    decode_base64_payload,
    decode_transport_body,
    find_query_credential,
    find_query_payload,
    ipv6_host_spans,
    is_allowlisted,
    is_base64_credential,
    is_base64_decodable_text,
    is_blank_query_value,
    is_constant_mac,
    is_cookie_attribute_metadata,
    is_cookie_attribute_name,
    is_fully_redacted,
    is_ipv6_host_address,
    is_mac_placeholder,
    is_mac_value,
    is_redacted,
    is_ssid_key,
    is_text_mime,
    iter_json_fields,
    iter_json_strings,
    iter_url_credentials,
    json_members,
    mac_layout,
    mime_kind,
    parse_json_container,
    query_param_segment,
    route_body,
    split_url_password,
    split_url_query,
    unredacted_identity,
    url_query,
)

__all__ = [
    # Pattern loading
    "load_pii_patterns",
    "load_sensitive_patterns",
    "load_allowlist",
    "load_capture_settings",
    "get_bloat_extensions",
    "get_password_field_patterns",
    "get_session_cookie_patterns",
    "clear_pattern_cache",
    "compile_pattern",
    "PatternLoadError",
    # Redaction checking and shared detection primitives
    "EMAIL_RE",
    "IPV6_RE",
    "JSON_MAX_DEPTH",
    "JSON_MAX_NESTING",
    "JsonObjectWithDuplicates",
    "MAC_RE",
    "PRIVATE_IP_RE",
    "PUBLIC_IP_RE",
    "QueryCredential",
    "QueryPayload",
    "classify_identity_field",
    "decode_base64_payload",
    "decode_transport_body",
    "find_query_credential",
    "find_query_payload",
    "json_members",
    "is_allowlisted",
    "is_blank_query_value",
    "is_constant_mac",
    "is_base64_credential",
    "is_base64_decodable_text",
    "is_cookie_attribute_metadata",
    "is_cookie_attribute_name",
    "is_fully_redacted",
    "is_ipv6_host_address",
    "is_mac_placeholder",
    "is_mac_value",
    "is_redacted",
    "is_ssid_key",
    "is_text_mime",
    "iter_json_fields",
    "iter_json_strings",
    "ipv6_host_spans",
    "iter_url_credentials",
    "mac_layout",
    "mime_kind",
    "parse_json_container",
    "query_param_segment",
    "route_body",
    "split_url_password",
    "split_url_query",
    "unredacted_identity",
    "url_query",
    "URL_VALUED_HEADERS",
    # Hashing
    "Hasher",
]
